# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destinacije',
            fields=[
                ('destinacija_id', models.AutoField(primary_key=True, serialize=False)),
                ('destinacija_naziv', models.CharField(max_length=50)),
                ('destinacija_opis', models.TextField()),
            ],
            options={
                'db_table': 'destinacije',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dnevnik',
            fields=[
                ('dnevnik_id', models.AutoField(primary_key=True, serialize=False)),
                ('dnevnik_korisnik', models.CharField(blank=True, max_length=50, null=True)),
                ('dnevnik_akcija', models.CharField(max_length=200)),
                ('dnevnik_vrijeme', models.DateTimeField()),
            ],
            options={
                'db_table': 'dnevnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sportovi',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_naziv', models.CharField(max_length=50)),
                ('sport_opis', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'sportovi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tereni',
            fields=[
                ('teren_id', models.AutoField(primary_key=True, serialize=False)),
                ('teren_naziv', models.CharField(max_length=200)),
                ('teren_opis', models.TextField()),
                ('slike_terena', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tereni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Termini',
            fields=[
                ('termin_id', models.AutoField(primary_key=True, serialize=False)),
                ('termin_opis', models.CharField(blank=True, max_length=255, null=True)),
                ('broj_dolazaka', models.IntegerField()),
                ('meksimalan_broj_dolazaka', models.IntegerField()),
            ],
            options={
                'db_table': 'termini',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('uloga_id', models.AutoField(primary_key=True, serialize=False)),
                ('uloga_naziv', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'uloge',
                'managed': False,
            },
        ),
    ]
