# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KorisnikTermin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'korisnik_termin',
                'managed': False,
            },
        ),
    ]
